// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// unnamed API: Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/JormungandrK/authorization-server/design
// --out=$(GOPATH)/src/github.com/JormungandrK/authorization-server
// --version=v1.2.0-dirty

package app
