// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// unnamed API: Application Security
//
// Command:
// $ goagen
// --design=github.com/Microkubes/authorization-server/design
// --out=$(GOPATH)/src/github.com/Microkubes/authorization-server
// --version=v1.2.0-dirty

package app

import (
	"context"
	"github.com/keitaroinc/goa"
	"net/http"
)

type (
	// Private type used to store auth handler info in request context
	authMiddlewareKey string
)

// UseOauth2ClientBasicAuthMiddleware mounts the oauth2_client_basic_auth auth middleware onto the service.
func UseOauth2ClientBasicAuthMiddleware(service *goa.Service, middleware goa.Middleware) {
	service.Context = context.WithValue(service.Context, authMiddlewareKey("oauth2_client_basic_auth"), middleware)
}

// NewOauth2ClientBasicAuthSecurity creates a oauth2_client_basic_auth security definition.
func NewOauth2ClientBasicAuthSecurity() *goa.BasicAuthSecurity {
	def := goa.BasicAuthSecurity{}
	def.Description = "Basic auth used by client to make the requests needed to retrieve and refresh access tokens"
	return &def
}

// UseOAuth2Middleware mounts the OAuth2 auth middleware onto the service.
func UseOAuth2Middleware(service *goa.Service, middleware goa.Middleware) {
	service.Context = context.WithValue(service.Context, authMiddlewareKey("OAuth2"), middleware)
}

// NewOAuth2Security creates a OAuth2 security definition.
func NewOAuth2Security() *goa.OAuth2Security {
	def := goa.OAuth2Security{
		Flow:             "accessCode",
		TokenURL:         "/oauth2/token",
		AuthorizationURL: "/oauth2/authorize",
		Scopes: map[string]string{
			"api:read":  "no description",
			"api:write": "no description",
		}}
	return &def
}

// handleSecurity creates a handler that runs the auth middleware for the security scheme.
func handleSecurity(schemeName string, h goa.Handler, scopes ...string) goa.Handler {
	return func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		scheme := ctx.Value(authMiddlewareKey(schemeName))
		am, ok := scheme.(goa.Middleware)
		if !ok {
			return goa.NoAuthMiddleware(schemeName)
		}
		ctx = goa.WithRequiredScopes(ctx, scopes)
		return am(h)(ctx, rw, req)
	}
}
