// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// unnamed API: public TestHelpers
//
// Command:
// $ goagen
// --design=github.com/Microkubes/authorization-server/design
// --out=$(GOPATH)/src/github.com/Microkubes/authorization-server
// --version=v1.2.0-dirty

package test
